# Generated by Django 3.0.8 on 2020-08-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType'),
        ),
    ]
