# Generated by Django 3.0.8 on 2020-08-22 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
