# Generated by Django 3.0.8 on 2020-08-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_comments_addtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(default='cover/t01.jpg', upload_to='cover/'),
        ),
    ]
